apiVersion: v2
name: symbolon
description: Helm chart for Symbolon Enterprise Licensing Server (ControlPlane)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - licensing
  - symbolon
  - controlplane
  - enterprise
maintainers:
  - name: MAGORS-organisation
