global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'symbolon-controlplane'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['controlplane:8080']
        labels:
          application: 'symbolon-controlplane'
          service: 'controlplane'
          environment: 'production'

  - job_name: 'symbolon-relay'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['relay:8081']
        labels:
          application: 'symbolon-relay'
          service: 'relay'
          environment: 'production'
