<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Achilles.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Achilles.Crypto\Achilles.Crypto.csproj" />
    <ProjectReference Include="..\Achilles.Format\Achilles.Format.csproj" />
    <ProjectReference Include="..\Achilles.Protocol\Achilles.Protocol.csproj" />
  </ItemGroup>

</Project>
