{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symbolon.fullname" . }}-db
  labels:
    {{- include "symbolon.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: "Host={{ .Values.database.host }};Port={{ .Values.database.port }};Database={{ .Values.database.name }};Username={{ .Values.database.username }};Password={{ .Values.database.password }}"
{{- end }}
